### PR TITLE
fix: set a default username

### LINKED ISSUE #54: FAILED to handle event: Error: Command failed: git config user.name
Hi, I just wanted to report that your nice extension (thx!) stopped working for me. I see the following error message.

image

### PR DESCRIPTION
**Pull request by mishraprafful**
## Related PRs/Issues
Closes #54 
Related to #49 

#### Changes
- Add a default username

#### Comments
None

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ function showDecoration(e: { readonly textEditor: vscode.TextEditor }) {
     cmd.stdin.end();
   }
 
-  const gitUser = cp.execSync("git config user.name").toString().trim();
+  const gitUser = cp.execSync("git config user.name").toString().trim() || "John Doe";
```
Comment (carlthome) [inline src/extension.ts:41]: Hehe, thanks!

Assume `git config user.name` returns an empty string and doesn't crash when unset.

**Review by carlthome — APPROVED** [review]

File: src/extension.ts (hunk 1 above)
Comment (mishraprafful) [reply src/extension.ts:41]: yes, tested that.
